include:
- ./functions/aircondition.zip
kind: ArchiveUploadSpec
name: functions-aircondition-zip-xjn2

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: aircondition
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-aircondition-zip-xjn2
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-17T01:11:56Z"
