include:
- ./functions/getdata.zip
kind: ArchiveUploadSpec
name: functions-getdata-zip-g0dc

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: getdata
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-getdata-zip-g0dc
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-19T15:21:58Z"
