include:
- ./functions/weathercondition.zip
kind: ArchiveUploadSpec
name: functions-weathercondition-zip-TMrX

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: weathercondition
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-weathercondition-zip-TMrX
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-15T11:31:24Z"
