apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: getfulldata
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: python
    namespace: ''
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: getfulldata.main
    packageref:
      name: getfulldata
      namespace: ''
  requestsPerPod: 1
  resources: {}
