include:
  - ./functions/getfulldata.zip
kind: ArchiveUploadSpec
name: functions-getfulldata-zip-QCI0

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: getfulldata
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ''
  source:
    checksum: {}
    type: url
    url: archive://functions-getfulldata-zip-QCI0
status:
  buildstatus: pending
  lastUpdateTimestamp: '2024-05-21T02:45:04Z'
