include:
- ./functions/put-database.zip
kind: ArchiveUploadSpec
name: functions-put-database-zip-Cfys

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: put-database
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-put-database-zip-Cfys
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-21T10:15:29Z"
