include:
  - ./functions/get-timeperioddata.zip
kind: ArchiveUploadSpec
name: functions-get-timeperioddata-zip-QWsz

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: get-timeperioddata
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ''
  source:
    checksum: {}
    type: url
    url: archive://functions-get-timeperioddata-zip-QWsz
status:
  buildstatus: pending
  lastUpdateTimestamp: '2024-05-21T02:56:54Z'
