apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: get-timeperioddata
spec:
  createingress: false
  functionref:
    functionweights: null
    name: get-timeperioddata
    type: name
  host: ''
  ingressconfig:
    annotations: null
    host: '*'
    path: /database/{datatype:[a-zA-Z0-9-]+}/{startdate:[0-9]{4}-[0-1][0-9]-[0-3][0-9]-[0-2][0-9]}/{enddate:[0-9]{4}-[0-1][0-9]-[0-3][0-9]-[0-2][0-9]}
    tls: ''
  method: ''
  methods:
    - GET
  prefix: ''
  relativeurl: /database/{datatype:[a-zA-Z0-9-]+}/{startdate:[0-9]{4}-[0-1][0-9]-[0-3][0-9]-[0-2][0-9]}/{enddate:[0-9]{4}-[0-1][0-9]-[0-3][0-9]-[0-2][0-9]}
