apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: getfulldata
spec:
  createingress: false
  functionref:
    functionweights: null
    name: getfulldata
    type: name
  host: ''
  ingressconfig:
    annotations: null
    host: '*'
    path: /database/{datatype:[a-zA-Z0-9-]+}
    tls: ''
  method: ''
  methods:
    - GET
  prefix: ''
  relativeurl: /database/{datatype:[a-zA-Z0-9-]+}
