include:
- ./functions/mastodon-aus-social.zip
kind: ArchiveUploadSpec
name: functions-mastodon-aus-social-zip-F4PP

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: mastodon-aus-social
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-mastodon-aus-social-zip-F4PP
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-19T07:43:42Z"
