apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: getfulldata
spec:
  createingress: false
  functionref:
    functionweights: null
    name: getdata
    type: name
  host: ''
  ingressconfig:
    annotations: null
    host: '*'
    path: /datatype/{datatype:[a-zA-Z0-9-]+}
    tls: ''
  method: ''
  methods:
    - GET
  prefix: ''
  relativeurl: /datatype/{datatype:[a-zA-Z0-9-]+}
